name: Build On PR

on:
  pull_request:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Verifying The Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Build Project
        run: npm run build
