name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  Continous-Deployment:
    name: Deploying The Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: isriramachandra/web-app:latest
      
      - name: Multiple commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker image prune -f
            sudo docker pull isriramachandra/web-app:latest
            sudo docker run -d --name web-app -p 3000:3000 isriramachandra/web-app:latest
      
